micronaut:
  application:
    name: order
  server:
    port: 8080
  codec:
    json:
      additionalTypes:
        - text/javascript
netty:
  default:
    allocator:
      max-order: 3

eureka:
  client:
    registration:
      enabled: true
    defaultZone: "${EUREKA_HOST:localhost}:${EUREKA_PORT:8761}"